### ISSUE TITLE
Bot crashes when an webhook message is sent

### ISSUE THREAD

**Issue by vermium** [VermiumSifell/xyter#567]
app           | Error: Member unavailable
app           |     at /dist/events/messageUpdate/audits.js:26:19
app           |     at Generator.next (<anonymous>)
app           |     at /dist/events/messageUpdate/audits.js:8:71
app           |     at new Promise (<anonymous>)
app           |     at __awaiter (/dist/events/messageUpdate/audits.js:4:12)
app           |     at Object.execute (/dist/events/messageUpdate/audits.js:21:42)
app           |     at /dist/events/messageUpdate/index.js:26:28
app           |     at Generator.next (<anonymous>)
app           |     at /dist/events/messageUpdate/index.js:8:71
app           |     at new Promise (<anonymous>)

It tries to send an messageUpdate with the webhook bot id, this crashes the bot I think.

**Comment by vermium** [comment]
Most probably solved by #629
